# numpy:  2D array (matrix) operations
2D arrays come with very powerful built-in matrix operations.
These allow you to perform an operation on every element of the matrix without any explicit iteration. E.g.,
 - simple map operations using math operators
 - matrix x scalar and matrix x matrix operations using math operators
 - create a boolean matrix using comparison operators

This makes for very concise and efficient code, but the code is a bit deceptive because unless you are cognizant that a variable refers to a numpy array, there is often no clue that a matrix operation is being performed.  Let's look at some examples...


In [1]:
import numpy as np

## Create a 2D array
 * simple: define it using a list of lists;
 * general: define it by supplying an (rows, cols) size;
 * random: filled with random values;
Notice that in some way we must always define the number of rows and columns (dimensions)

In [2]:
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
ones = np.ones((3, 3), dtype='uint8')
rand = np.random.randint(2, size=(3, 3), dtype='uint8')
matrix, ones, rand

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=uint8),
 array([[0, 1, 0],
        [0, 0, 0],
        [1, 1, 1]], dtype=uint8))

## Matrix x Scalar operations
numpy array class defines all math and comparison operators.
Confusion arises here b/c the code itself does not indicate there is a matrix operation being done - you have to know!

In [3]:
double = matrix * 2
twos = ones + 1
alive = rand == 1
double, twos, alive

(array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=uint8),
 array([[False,  True, False],
        [False, False, False],
        [ True,  True,  True]]))

## Matrix x Matrix operations
All operators also work when both arguments are arrays, in this case operations are done pair-wise on matching elements.
The 2 arrays must have the same shape!

In [4]:
squares = matrix * matrix
threes = ones + twos
filtered = rand * matrix
squares, threes, filtered

(array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]),
 array([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]], dtype=uint8),
 array([[0, 2, 0],
        [0, 0, 0],
        [7, 8, 9]]))

## Logical operators
numpy does not re-define python's built-in logical operators `and`, `or`, `not`
But it does define the "bitwise" operators, bitwise and `&`, bitwise or `|` and bitwise not '~'.
With care, these can be used to implement whole-matrix logical operations...
**Tips**: both operands should by `bool` or `0`/`1` valued arrays (or you better really understand bitwise operators!).
     Watch your precedence -- bitwise operators are very low precedence!

In [5]:
try:
    alive and matrix
except ValueError as e:
    print('Error:', e)

fitlered2 = alive & matrix!=0
big_and_alive = (matrix > 5) & alive
not_alive = ~alive
fitlered2, big_and_alive, not_alive

Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


(array([[False, False, False],
        [False, False, False],
        [ True, False,  True]]),
 array([[False, False, False],
        [False, False, False],
        [ True,  True,  True]]),
 array([[ True, False,  True],
        [ True,  True,  True],
        [False, False, False]]))

## Matrix indexing
Perhaps one of the most powerful numpy array operations is the ability to use the values of one array as indexes to lookup values in another array.
For this operation the arrays can be different sizes and shapes, but you need to be clear about which array is the lookup table and which is the indexes!

In [6]:
month_names = np.array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
month_nums = np.random.randint(low=1, high=12, size=(5, 5))
month_nums, month_names[month_nums-1]

(array([[ 3,  5,  9,  9,  9],
        [10,  8, 10,  5,  1],
        [ 7,  2,  6, 11,  9],
        [ 6,  9,  2, 11, 11],
        [ 4,  6, 10,  6,  3]]),
 array([['Mar', 'May', 'Sep', 'Sep', 'Sep'],
        ['Oct', 'Aug', 'Oct', 'May', 'Jan'],
        ['Jul', 'Feb', 'Jun', 'Nov', 'Sep'],
        ['Jun', 'Sep', 'Feb', 'Nov', 'Nov'],
        ['Apr', 'Jun', 'Oct', 'Jun', 'Mar']], dtype='<U3'))

### Filter with Boolean indexes
By using an array of booleans, you can filter out a set of elements from another array with the same shape.

In [7]:
even_squares = squares[squares%2==0]
squares, even_squares

(array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]),
 array([ 4, 16, 36, 64]))

Notice you get back a simple 1D array of elements.  These can act as references back to elements in the original array.
This allows us to use a scalar assignment to update elements of the original 2D array that meet some criteria ...

In [8]:
matrix_dead = matrix.copy()
matrix_dead[~alive] = 0
alive, matrix_dead

(array([[False,  True, False],
        [False, False, False],
        [ True,  True,  True]]),
 array([[0, 2, 0],
        [0, 0, 0],
        [7, 8, 9]]))